name: SBOM (CycloneDX)
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.sh"
      - "**/*.ts"
      - "**/*.go"
      - ".github/**"
      - "Makefile"
      - "workstation/**"
      - "gcloud/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  actions: read
  id-token: write
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v0
      - name: Generate SBOM
        run: |
          syft packages dir:. -o cyclonedx-json > sbom.cdx.json
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom.cdx.json
          path: sbom.cdx.json
