name: OpenSSF Scorecard
on:
  push:
    branches: [ "main" ]
    paths:
      - "**/*.sh"
      - "**/*.ts"
      - "**/*.go"
      - ".github/**"
      - "Makefile"
      - "workstation/**"
      - "gcloud/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**/*.sh"
      - "**/*.ts"
      - "**/*.go"
      - ".github/**"
      - "Makefile"
      - "workstation/**"
      - "gcloud/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
  id-token: write
  security-events: write
jobs:
  scorecard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Scorecard
        uses: ossf/scorecard-action@v4
        with:
          results_file: results.sarif
          results_format: sarif
      - name: Upload SARIF to Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
